const IDENTIFIER = '@@player';

const FETCH_SONG_REQUEST = `${IDENTIFIER}FETCH_SONG_REQUEST`;
const FETCH_SONG_SUCCESS = `${IDENTIFIER}FETCH_SONG_SUCCESS`;
const FETCH_SONG_FAILURE = `${IDENTIFIER}FETCH_SONG_FAILURE`;

const TRACK_NEXT = `${IDENTIFIER}TRACK_NEXT`;
const TRACK_PREV = `${IDENTIFIER}TRACK_PREV`;
const TRACK_SHUFFLE = `${IDENTIFIER}TRACK_SHUFFLE`;
const TRACK_CURRENT = `${IDENTIFIER}TRACK_CURRENT`;
const TRACK_DELETE = `${IDENTIFIER}TRACK_DELETE`;

const FIND_TRACK_SUCCESS = `${IDENTIFIER}FIND_TRACK_SUCCESS`;
const FIND_TRACK_FAILURE = `${IDENTIFIER}FIND_TRACK_FAILURE`;
const FIND_TRACK_ADDED = `${IDENTIFIER}FIND_TRACK_ADDED`;
const CLEAR_SEARCH_LIST = `${IDENTIFIER}CLEAR_SEARCH_LIST`;

export {
    FETCH_SONG_REQUEST,
    FETCH_SONG_SUCCESS,
    FETCH_SONG_FAILURE,
    TRACK_NEXT,
    TRACK_PREV,
    TRACK_SHUFFLE,
    TRACK_CURRENT,
    TRACK_DELETE,
    FIND_TRACK_SUCCESS,
    FIND_TRACK_FAILURE,
    FIND_TRACK_ADDED,
    CLEAR_SEARCH_LIST
}