const IDENTIFIER = '@@player';

const FETCH_SONG_REQUEST = `${IDENTIFIER}FETCH_SONG_REQUEST`;
const FETCH_SONG_SUCCESS = `${IDENTIFIER}FETCH_SONG_SUCCESS`;
const FETCH_SONG_FAILURE = `${IDENTIFIER}FETCH_SONG_FAILURE`;

const TRACK_NEXT = `${IDENTIFIER}TRACK_NEXT`;
const TRACK_PREV = `${IDENTIFIER}TRACK_PREV`;
const TRACK_SHUFFLE = `${IDENTIFIER}TRACK_SHUFFLE`;
const TRACK_CURRENT = `${IDENTIFIER}TRACK_CURRENT`;

const FIND_TRACK_SUCCESS = `${IDENTIFIER}FIND_TRACK_SUCCESS`;
const FIND_TRACK_FAILURE= `${IDENTIFIER}FIND_TRACK_FAILURE`;

export {
    FETCH_SONG_REQUEST,
    FETCH_SONG_SUCCESS,
    FETCH_SONG_FAILURE,
    TRACK_NEXT,
    TRACK_PREV,
    TRACK_SHUFFLE,
    TRACK_CURRENT,
    FIND_TRACK_SUCCESS,
    FIND_TRACK_FAILURE
}