const IDENTIFIER = 'player';

const FETCH_SONG_REQUEST = `${IDENTIFIER}FETCH_SONG_REQUEST`;
const FETCH_SONG_SUCCESS = `${IDENTIFIER}FETCH_SONG_SUCCESS`;
const FETCH_SONG_FAILURE = `${IDENTIFIER}FETCH_SONG_FAILURE`;

export {
    FETCH_SONG_REQUEST,
    FETCH_SONG_SUCCESS,
    FETCH_SONG_FAILURE
}